model:
  base_learning_rate: 2.0e-04
  target: ldm.models.diffusion.ddpm_edit.LatentDiffusion
  params:
    ckpt_path: checkpoints/instruct-pix2pix-00-22000.ckpt
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 50
    timesteps: 1000
    first_stage_key: edited
    cond_stage_key: edit
    image_size: 32
    channels: 4
    cond_stage_trainable: false
    conditioning_key: hybrid
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: true
    load_ema: true
    scheduler_config:
      target: ldm.lr_scheduler.LambdaWarmUpCosineScheduler
      params:
        warm_up_steps: 400
        max_decay_steps: 15000
        lr_start: 0.0
        lr_max: 1.0
        lr_min: 1.0e-06
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 8
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 128
    num_workers: 4
    train:
      target: edit_dataset_manual_edits.EditDataset
      params:
        path: /mmfs1/gscratch/krishna/psushko/photobench/finetuning2/instruct-pix2pix/data/ssim_filtered
        split: train
        splits:
        - 1.0
        - 0.0
        - 0.0
        min_resize_res: 256
        max_resize_res: 256
        crop_res: 256
        flip_prob: 0.0
    validation:
      target: edit_dataset_manual_edits.EditDataset
      params:
        path: /gscratch/krishna/psushko/photobench/finetuning2/instruct-pix2pix/data/cleaned_reddit_data_val
        split: val
        splits:
        - 0.0
        - 1.0
        - 0.0
        min_resize_res: 256
        max_resize_res: 256
        crop_res: 256
